### ISSUE TITLE
Pop-up window

### ISSUE THREAD

**Issue by PaulChuma** [mehrvarz/webcall-android#10]
When a call comes in, only an audible alert will sound.
Please add a pop-up window with the ability to accept or reject the call.

**Comment by mehrvarz** [comment]
Hi. It is not only the audio signal (ring tone). When a call arrives, the screen will turn on and the WebCall activity will jump to the front, where you can accept or decline. On what type of device does this not work?

**Comment by PaulChuma** [comment]
I am the owner of a OnePlus 9 Pro 5G smartphone. Unfortunately, when a call is received on the WebCall application, there is only a sound signal.
WebView: 103.0.5060.129

**Comment by mehrvarz** [comment]
When the screen is off and you receive a call, does the screen turn on? What are you then looking at? When a call arrives, can you navigate to WebCall app manually and answer the call? What version is shown when you open: hamburger menu -> Device menu?

**Comment by PaulChuma** [comment]
_When the screen is off and you receive a call, does the screen turn on?_ - No. The screen does not turn on, but I hear the sound. I unlock the phone and take out the application from the curtain.

**Comment by PaulChuma** [comment]
_When the screen is off and you receive a call, does the screen turn on?_ - No. The screen does not turn on, but I hear the sound. I unlock the phone and take out the application from the curtain.

**Comment by PaulChuma** [comment]
_When a call arrives, can you navigate to WebCall app manually and answer the call?_ - Yes, I have to search for the application manually or from the curtain or from the application menu.

**Comment by PaulChuma** [comment]
_When a call arrives, can you navigate to WebCall app manually and answer the call?_ - Yes, I have to search for the application manually or from the curtain or from the application menu.

**Comment by PaulChuma** [comment]
_What are you then looking at?_ - Unfortunately, nothing happens. I hear only the sound of a call.

**Comment by PaulChuma** [comment]
_What version do you have?_ - Right now I'm using version 1.0.7F. Version 1.0.7T has exactly the same functionality, the difference is only in the signature.

**Comment by mehrvarz** [comment]
> The screen does not turn on, but I hear the sound.

There are 2 ways you can receive webcalls on Android: app and webapp. Both ring on incoming calls. But only the app can turn the screen on and bring itself to the front. In case you run both: full exit the app and see if you can still receive calls.

**Comment by PaulChuma** [comment]
I only use the android app. If I exit the application, I will not be able to receive calls in any way.

**Comment by mehrvarz** [comment]
You are totally correct. This problem exists and I somehow didn't notice it. A solution will become available soon. I will contact you here when it is ready.

**Comment by mehrvarz** [comment]
Would this fit your expectations?

![WebCallNotif](https://user-images.githubusercontent.com/205967/184592491-b91a7ea1-ebab-45a5-ba76-445e9c4fada4.jpg)

**Comment by PaulChuma** [comment]
> Would this fit your expectations?
> 
> ![WebCallNotif](https://user-images.githubusercontent.com/205967/184592491-b91a7ea1-ebab-45a5-ba76-445e9c4fada4.jpg)
> 
> Edit: New client v1.1 is available for download (Aug 16)

The appearance of the pop-up window is not so important.The main thing is its functionality.

**Comment by PaulChuma** [comment]
> Would this fit your expectations?
> 
> ![WebCallNotif](https://user-images.githubusercontent.com/205967/184592491-b91a7ea1-ebab-45a5-ba76-445e9c4fada4.jpg)
> 
> Edit: New client v1.1 is available for download (Aug 16)

The appearance of the pop-up window is not so important.The main thing is its functionality.

**Comment by mehrvarz** [comment]
> The appearance of the pop-up window is not so important.The main thing is its functionality.

I agree

**Comment by mehrvarz** [comment]
Are you satisfied with the way it works?

**Comment by PaulChuma** [comment]
> Are you satisfied with the way it works?

Timur, 
In my opinion, you are doing a very interesting and useful project.
And I hope you don't give up.
At the moment, your project is quite crude and in terms of stability and convenience it loses a lot to its competitors.
If you don't mind, I'll be happy to help you as much as I can. And you will be able to find a new platform for you to distribute your project and increase the user market.

**Comment by mehrvarz** [comment]
Did you have a chance to look at the v1.1.5 release from 24h ago? I think the issues you are referring to have been fully resolved.
