### ISSUE TITLE
Can the ringtone be changed manually?

### ISSUE THREAD

**Issue by NCHU611A** [mehrvarz/webcall-android#14]
Hi,
Is there a function to change the ringtone music?
I want to change the ringtone music to my favorite music.
But I didn't see the **.mp3** file in the folder.
So I want to ask you what if I want to change the ringtone music.
Thank you.

**Comment by mehrvarz** [comment]
Normally the ringtone cannot be changed.

If you run your own webcall server you may be able to replace "webroot/callee/1980-phone-ringing.mp3". But this will only affect your web clients. WebCall Android client has it's own ringtone embedded inside so it can play a ringtone also if activity+webview are unloaded.

**Comment by NCHU611A** [comment]
> Normally the ringtone cannot be changed.
> 
> If you run your own webcall server you may be able to replace "webroot/callee/1980-phone-ringing.mp3". But this will only affect your web clients.

I understand, thank you.

> WebCall Android client has it's own ringtone embedded inside so it can play a ringtone **also if activity+webview are unloaded.**

But I don't quite understand what this sentence means, sorry.

Thank you.

**Comment by mehrvarz** [comment]
WebCall Android client does not fetch the ringtone from the server. It has the ringtone file already built in (src/main/res/raw/ringing.ogg). If you build the Android client from source, you can replace the ringtone here as well.

**Comment by NCHU611A** [comment]
Ok!
Thank you!
