### ISSUE TITLE
Current Apr11 v1.2.7 apk says it is outdated

### ISSUE THREAD

**Issue by dagelf** [mehrvarz/webcall-android#18]
As a consequence wont go online

**Comment by mehrvarz** [comment]
Any Android client since v1.1.0 (August 16, 2022) should get access. This has to be an exceptional situation. What is the exact error message you get? Can you try to log in with just a web browser? Would be helpful to know if this works better, or not.

**Comment by mehrvarz** [comment]
not reproducible
