### ISSUE TITLE
Nice project, keep on working!

### ISSUE THREAD

**Issue by NanyangTaiji** [mehrvarz/webcall-android#4]
Just wonder whether the server has the capacity to intercept the voice and video for particular call id?

**Comment by mehrvarz** [comment]
All audio/video exchange is managed by the WebCall client running on the device. WebCall client is making textbook use of WebRTC. The WebRTC engine on the device is alone responsible for establishing an e2e-encrypted link between the devices. All audio/video is then sent over this encrypted link. WebCall server is not involved in this. And like any 3rd party, it can not intercept the e2e-encrypted data. Let me know if you need more info on this.
